services:
  database:
    env_file: .env  # For√ßa o carregamento do arquivo .env
    image: ${DB_TYPE}:${DB_VERSION}
    container_name: db_ccp_${DB_TYPE}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_ROOT_PASSWORD: root_password_aqui
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      # Volume mapeado para uma pasta local definida no .env
      - ${DB_VOLUME_PATH}:/var/lib/${DB_TYPE}/data
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app_ccp
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:${DB_TYPE}://database:${DB_PORT}/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
